// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA7c0fsFNsDqlcAGusxjmOQu4ymI3Pgrgc',
    appId: '1:784594753558:web:441160eedb3848d9c77d37',
    messagingSenderId: '784594753558',
    projectId: 'amul-c27e3',
    authDomain: 'amul-c27e3.firebaseapp.com',
    storageBucket: 'amul-c27e3.appspot.com',
    measurementId: 'G-227K4SR4X9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBk5kdOZNvXQmzFdEv4ykw50423j82uE_4',
    appId: '1:784594753558:android:abe84a0085c95806c77d37',
    messagingSenderId: '784594753558',
    projectId: 'amul-c27e3',
    storageBucket: 'amul-c27e3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJ0I3KtR4IUSeofPf3-SoQ0Us1lY-KQJM',
    appId: '1:784594753558:ios:0fcb6f44822440dbc77d37',
    messagingSenderId: '784594753558',
    projectId: 'amul-c27e3',
    storageBucket: 'amul-c27e3.appspot.com',
    iosBundleId: 'com.example.amul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJ0I3KtR4IUSeofPf3-SoQ0Us1lY-KQJM',
    appId: '1:784594753558:ios:2dea1c2664691800c77d37',
    messagingSenderId: '784594753558',
    projectId: 'amul-c27e3',
    storageBucket: 'amul-c27e3.appspot.com',
    iosBundleId: 'com.example.amul.RunnerTests',
  );
}
